---
title: "Financial Big Data Quiz 5"
author: "108070014  陳品妤"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 4
    number_sections: false
---

<style type = "text/css">
  body{
    font-family: "Cambria";
    font-size: 18px;
    text-align: justify;
  }
  h1.title{
    text-align: center;
    font-size: 40px;
  }
  .author{
    text-align: center;
    font-size: 24px;
    font-family: "Cambria", "標楷體";
  }
</style>

```{r, warning = FALSE, message = FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      comment = "", 
                      dev.args = list(bg = 'lavender',                                       pointsize = 11))
library(magrittr)
library(stats)      # must load 'stats' before 'tidyverse' so that default 'filter()' function comes from 'tidyverse' 
library(tidyverse)
library(nycflights13)
options(dplyr.summarise.inform = FALSE)
temp = Sys.setlocale("LC_ALL","English.UTF-8")
library(xts)
library(tsibble)
library(lubridate)
library(skimr)
library(kableExtra)
ptable = function(df,digits = getOption("digits"),size = 14){
  df %>% knitr::kable(digits = digits) %>% 
    kable_classic(lightable_options = c("striped", "hover", "condensed"),
                  fixed_thead = list(enabled = T, 
                                     background = "lavender"),
                  font_size = size, full_width = F,
                  html_font = "helvetica")
}
library(dplyr)
library(ggplot2)
```

### Question 1
Given plot:
```{r}
mpg %>% ggplot + 
  geom_bar(aes(class,after_stat((count - median(count))),fill = class),
           show.legend = F) +
  ylab("Deviation from the Median")
?after_stat()
?geom_col()
```

```{r echo=TRUE, results='hide', eval=FALSE}
mpg %>%
  group_by(class) %>%
  mutate(deviation = as.numeric(count) - median(as.numeric(count))) %>%
  ggplot() +
  geom_col(aes(class, deviation, fill = class), show.legend = FALSE) +
  ylab("Deviation from the Median")
```

```{r, echo=FALSE}
mpg %>% ggplot + 
  geom_bar(aes(class,after_stat((count - median(count))),fill = class),
           show.legend = F) +
  ylab("Deviation from the Median")
```


